FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

ENV DB_HOST=postgres\
    DB_DATABASE=permalist\
    DB_USER=honeybhandari\
    DB_PASSWORD=honey123\
    DB_PORT=5432

EXPOSE 3000

CMD ["npm","start"]
